# Generated by Django 4.0.5 on 2022-08-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lang',
            field=models.CharField(default='English', max_length=1000000),
        ),
    ]
