# Generated by Django 4.0.5 on 2022-08-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetranslate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleimage',
            name='lang',
            field=models.CharField(default='English', max_length=1000000),
        ),
    ]
